### ISSUE TITLE
Convert other AirTable tables to new benefitEligibility format

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1692]

**Comment by SupeDeDupe** [comment]
After talking a bit with Allison about next steps admin editing options, it seems like maybe we should link benefits from benefitEligibility in nextSteps in Airtable, and have additional fields linking to multipleChoiceOptions so that broader categories of benefits can be associated with certain next steps.

**Comment by smcmurtry** [comment]
@SupeDeDupe I think we should do this issue anyway so we can delete the eligibilityPaths sheet so that there's no confusion for people trying to edit eligibility data in the wrong place.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change eligibility path structure to be more like Allison's spreadsheet](https://trello.com/c/KXov9hiW/148-change-eligibility-path-structure-to-be-more-like-allisons-spreadsheet)
