### ISSUE TITLE
Add pop-up

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1974]
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c82797c4f5a3bbcc640ce92
<img width="935" alt="screen shot 2019-03-08 at 10 25 57 am" src="https://user-images.githubusercontent.com/17673146/54034166-93a80600-418c-11e9-939c-c246cde89bdd.png">

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add popup disclaimer to the tool with the approved messaging from comms](https://trello.com/c/cgJ5WtPr/230-add-popup-disclaimer-to-the-tool-with-the-approved-messaging-from-comms)

**Comment by courtneycl** [comment]
will there be a pop up for mobile? 

I recommend not having one since the beta banner is front and centre on mobile, and it's confusing to close a pop up and have the exact same messaging be the focus: 
![image](https://user-images.githubusercontent.com/3474250/54366253-b6cc2d00-4646-11e9-9dc8-ef48e809a64b.png)

**Comment by PeterBarrett2** [comment]
I agree, that's too much, and the banner in this instance serves the exact same purspose.
