### ISSUE TITLE
Put title on one line rather than two

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#374]
![bb41c6bc-375e-4571-9e6e-c6a45354c9c5](https://user-images.githubusercontent.com/8228248/41509102-d689e050-721c-11e8-9368-8592a3108915.jpeg)

**Comment by smcmurtry** [comment]
So this is because we're allocating 33% of the width to the title and 67% to the jump buttons on medium screens:
<img width="1186" alt="screen shot 2018-06-18 at 10 01 50 am" src="https://user-images.githubusercontent.com/5498428/41541021-7740e67a-72df-11e8-94db-0fe3452233b0.png">

And this is what it looks like if we do 50%/50%:
<img width="1198" alt="screen shot 2018-06-18 at 10 09 30 am" src="https://user-images.githubusercontent.com/5498428/41541143-c943def0-72df-11e8-9cc6-73253cc1cf66.png">

**Comment by maxneuvians** [comment]
Could we put the jump buttons on a new line?

**Comment by sastels** [comment]
Ah, gotcha, I thought it might be a bug. Maybe it's fine the way it is then. Let's just close this for now, and reopen in the future if Design wants it differently.
